feed.frequency=1000

kafka.bootstrap.servers=localhost:9092

kafka.topic.name=news-topic

kafka.group.id=news-analyzer-group

key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=org.apache.kafka.common.serialization.StringSerializer

key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

auto.offset.reset=latest